server.port=8085
spring.application.name=ms-sam

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=${DB_SAM_URL:jdbc:mysql://localhost:3306/db_sam?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_SAM_USER:root}
spring.datasource.password=${DB_SAM_PASS:Sps2026!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.rabbitmq.host=${RABBITMQ_HOST:10.43.99.13}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:sps_user}
spring.rabbitmq.password=${RABBITMQ_PASS:sps_pass}

spring.jackson.serialization.write-dates-as-timestamps=false

app.jwt.secret=${JWT_SECRET:supersecretkey256bitsminimum1234567890}
