<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FrontendSaludPay</AssemblyName>
    <RootNamespace>SPS.SaludPay.Frontend</RootNamespace>
  </PropertyGroup>

</Project>
