server.port=8081
spring.application.name=ms-auth

# Datasource
spring.datasource.url=${DB_AUTH_URL:jdbc:mysql://localhost:3306/db_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_AUTH_USER:root}
spring.datasource.password=${DB_AUTH_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT
app.jwt.secret=${JWT_SECRET:supersecretkey256bitsminimum1234567890}

# Logging
logging.level.com.sps.auth=INFO
