upstream compra_backend {
    server ms-compra:8082;
}

upstream sns_backend {
    server ms-sns:8083;
}

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;

    location /api/auth/ {
        proxy_pass http://host.docker.internal:8081/ws/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/compra/ {
        proxy_pass http://compra_backend/ws/compra/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/sns/ {
        proxy_pass http://sns_backend/ws/sns/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /saludpay/ {
        proxy_pass http://saludpay-frontend:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
