upstream compra_backend {
    server 10.43.99.13:8082;
}

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;

    location /api/auth/ {
        proxy_pass http://10.43.100.66:8081/ws/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/compra {
        rewrite ^/api/compra(/.*)?$ /ws/compra$1 break;
        proxy_pass http://compra_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /saludpay/ {
        proxy_pass http://saludpay-frontend:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/sns/ {
        proxy_pass http://10.43.99.13:8083/ws/sns/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
